
import Head from "next/head";
import {

  Card,
  Row,
  Col,
  Button,

} from "reactstrap";
import jwt from 'jsonwebtoken'
import Profile from '../../src/components/Profile';
import MainContext from "../../src/app/context/context";
import React, { useContext, useState, useEffect } from "react";
import FullLayout from "../../src/layouts/FullLayout";
import Swal from "sweetalert2";
const UserProfile = () => {
  const [currentUser, setCurrentUser] = useState({
    firstName:"", lastName:"",dateOfBirth:"",phoneNumber:"", gender:"", email:"", role:"",
    specialty:"", availability:"", hospitalLocation:"", hospitalName:"", biography:"",
    details:"", profile:""
  })
  const global = useContext(MainContext);
  const getUserData = async()=>{
    try {
      const token = localStorage.getItem("authToken")
      const secret = 'weightLoser@3rdEyeSof!@123!';
      const user = jwt.verify(token, secret);
      const currentUserFetch = await global?.getCurrentUser(user.id);
      if (currentUserFetch.status) {
        setCurrentUser(currentUserFetch.result.data);
      }
    } catch (error) {
      console.log(error.message)
      Swal.fire({
        icon: 'error',
        title: 'Oops...',
        text: 'Something went wrong!, While Fetching Doctors',
      })
    }
  }
  useEffect(() => {
    getUserData()
 // eslint-disable-next-line react-hooks/exhaustive-deps
 }, [])

  const onDismiss = () => {
    setVisible(false);
  };

  return (
    <FullLayout>
      <div>
        <Head>
          {/* <title>Alert Page - Xtreme Starter Next Js App</title> */}
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Row style={{ backgroundColor: global?.theme?.backgroundColor, color: global?.theme?.color }} className="prosect">
          <Col lg="10" md="10" sm="12" className="propic">
            <div className="proimage">
              <img src={currentUser?.profile} alt="profileimageofuser"></img>
              <div className="propicinner"><h2>{currentUser?.firstName} {currentUser?.lastName}</h2>
                <p>Powered by <b>Well Clinics</b></p>
              </div>
            </div>
          </Col>
          <Col lg="2" md="2" sm="12" className="btntwo">
            <Button>Save</Button>
          </Col>
        </Row>
        <Card >
          <Profile currentUser={currentUser} />
        </Card>
      </div>
    </FullLayout>
  );
};

export default UserProfile;
